version: "3.8"

services:
  nextjs:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/app
    environment:
      - NODE_ENV=production
      - POCKETBASE_URL=http://pocketbase:8080
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./nextjs-app/.env.production

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8080:8080"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pocketbase_data:
  pocketbase_public:
